// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kfesogcncqoazwjvnslk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtmZXNvZ2NuY3FvYXp3anZuc2xrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc1MTM3MDAsImV4cCI6MjA2MzA4OTcwMH0.ospVoTIBCq8j62kgpwzopIYyaqH0lc5HpmdwwK3nEdo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);